export default {
    ERROR_ROUTE_POSITIONS_EMPTY: 'ERROR_ROUTE_POSITIONS_EMPTY',
    ERROR_ROUTE_STARTTIME_REQUIRED: 'ERROR_ROUTE_STARTTIME_REQUIRED',
    ERROR_ROUTE_ENDTIME_REQUIRED: 'ERROR_ROUTE_ENDTIME_REQUIRED',
    ERROR_ROUTE_ENDTIME_BEFORE_STARTTIME: 'ERROR_ROUTE_ENDTIME_BEFORE_STARTTIME',
    ERROR_POSITION_LATITUDE_NOTANUMBER: 'ERROR_POSITION_LATITUDE_NOTANUMBER',
    ERROR_POSITION_LATITUDE_NULLORUNDEFINED: 'ERROR_POSITION_LATITUDE_NULLORUNDEFINED',
    ERROR_POSITION_LONGITUDE_NOTANUMBER: 'ERROR_POSITION_LONGITUDE_NOTANUMBER',
    ERROR_POSITION_LONGITUDE_NULLORUNDEFINED: 'ERROR_POSITION_LONGITUDE_NULLORUNDEFINED',
    ERROR_POSITION_TIME_REQUIRED: 'ERROR_POSITION_TIME_REQUIRED',
    ERROR_POSITION_TIMEISINTHEPAST: 'ERROR_POSITION_TIMEISINTHEPAST'

};
